// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = never
type PageRoutes = "/" | "/_app" | "/_document" | "/aixcelerator" | "/aixcelerator/agents" | "/aixcelerator/agents/[slug]" | "/aixcelerator/mcp" | "/aixcelerator/mcp/[slug]" | "/aixcelerator/skills" | "/aixcelerator/skills/[slug]" | "/assistant" | "/cookie-policy" | "/industries" | "/industries/[industry]" | "/internal/catalog-health" | "/internal/newsletter-report" | "/llms-full.txt" | "/privacy-policy" | "/request-demo" | "/resources" | "/resources/articles" | "/resources/articles/[slug]" | "/resources/books" | "/resources/case-studies" | "/resources/podcasts" | "/resources/podcasts/[slug]" | "/resources/podcasts/company" | "/resources/podcasts/tag/[tag]" | "/resources/white-papers" | "/robots.txt" | "/search" | "/sitemap.xml" | "/solutions" | "/unsubscribe" | "/updates" | "/use-cases" | "/use-cases/[slug]"
type LayoutRoutes = never
type RedirectRoutes = never
type RewriteRoutes = "/articles" | "/podcast/[slug]" | "/podcasts" | "/resources/podcasts/company/[slug]"
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes


interface ParamMap {
  "/": {}
  "/_app": {}
  "/_document": {}
  "/aixcelerator": {}
  "/aixcelerator/agents": {}
  "/aixcelerator/agents/[slug]": { "slug": string; }
  "/aixcelerator/mcp": {}
  "/aixcelerator/mcp/[slug]": { "slug": string; }
  "/aixcelerator/skills": {}
  "/aixcelerator/skills/[slug]": { "slug": string; }
  "/articles": {}
  "/assistant": {}
  "/cookie-policy": {}
  "/industries": {}
  "/industries/[industry]": { "industry": string; }
  "/internal/catalog-health": {}
  "/internal/newsletter-report": {}
  "/llms-full.txt": {}
  "/podcast/[slug]": { "slug": string; }
  "/podcasts": {}
  "/privacy-policy": {}
  "/request-demo": {}
  "/resources": {}
  "/resources/articles": {}
  "/resources/articles/[slug]": { "slug": string; }
  "/resources/books": {}
  "/resources/case-studies": {}
  "/resources/podcasts": {}
  "/resources/podcasts/[slug]": { "slug": string; }
  "/resources/podcasts/company": {}
  "/resources/podcasts/company/[slug]": { "slug": string; }
  "/resources/podcasts/tag/[tag]": { "tag": string; }
  "/resources/white-papers": {}
  "/robots.txt": {}
  "/search": {}
  "/sitemap.xml": {}
  "/solutions": {}
  "/unsubscribe": {}
  "/updates": {}
  "/use-cases": {}
  "/use-cases/[slug]": { "slug": string; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }
}
